<a href="https://colab.research.google.com/github/Umang305/Clever/blob/master/Enablement_and_Engagement_of_Parents_at_Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Enablement and Engagement of Parents at Work**

In [2]:
import numpy as np
import pandas as pd

In [4]:
train_data = pd.read_csv("/content/drive/MyDrive/ctrl-del-hack-dataset/Train.csv")

In [5]:
train_data.head(20)

    Employee ID WFH Setup Available  ... Health Conditions               Support
0         17052                  No  ...               Yes                Leaves
1          9196                 Yes  ...                No                Career
2         25566                  No  ...               Yes  Caregiving Programme
3            84                  No  ...                No                Career
4         10929                 Yes  ...                No                Career
5         21627                 Yes  ...                No                Career
6          8050                 Yes  ...               Yes             Ergonomic
7          2733                  No  ...                No                Others
8           171                 Yes  ...               Yes                Others
9         26129                 Yes  ...                No                Leaves
10        20202                  No  ...               Yes                Leaves
11        10606                  No  ...                No                Leaves
12        27662                  No  ...               Yes  Caregiving Programme
13        18405                  No  ...               Yes  Caregiving Programme
14         3723                 Yes  ...               Yes             Ergonomic
15        14248                  No  ...                No  Caregiving Programme
16        15149                  No  ...                No             Ergonomic
17        22437                 Yes  ...               Yes                Leaves
18        20484                  No  ...                No                Others
19        29693                  No  ...                No  Caregiving Programme

[20 rows x 22 columns]